### PR TITLE
upgrade dependencies, most notably: jcmturner/gokrb5(v4->v5)

### PR DESCRIPTION
**Pull request by jcmturner**
Update to v5 of gokrb5.

I have not been able to test the plugin as I don't have an environment to test in.

### CODE REVIEW

**Comment by jcmturner** [comment]
Hi, this seems to work for upgrading the version of gokrb5 from v4 to v5. However I can't agree to the CLA as it implies that I am giving up all rights to the code that is checked in to this repo. This may be interpreted to include that which is in the vendor directory.

**Comment by pault28** [comment]
@jcmturner I will give this a test as we actively use this plugin. See now closed https://github.com/jcmturner/gokrb5/issues/156. Also this is related to https://github.com/wintoncode/vault-plugin-auth-kerberos/issues/9

@ah- Any chance of reviewing this?

**Comment by ah-** [comment]
Wonderful, thanks for this! Changes look good, if @pault28 s testing works out I'll merge.

**Comment by pault28** [comment]
@ah- this works perfectly fine for windows and linux clients. +1 to merge.

**Comment by ah-** [comment]
All there now, thanks for testing @pault28!

**Pull request merged**
